######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 26 18:18:20 2016
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lifetracker.h
SOURCES += lifetracker.cpp main.cpp

QT += widgets
